
var label Label = na

DAY_IN_MILLISECONDS = 86400000

days_til_expiration = round((expiration_date - time) / DAY_IN_MILLISECONDS)

label.delete(Label)

label_x_position = expiration_date + round(change(time) * info_offset)
label_y_position = strike_price

dollars_itm = above_strike ? close - strike_price : strike_price - close

emoji = above_strike ? get_itm_emoji(dollars_itm) : get_otm_emoji(dollars_itm)

var _text = ""

_text := syminfo.description + "\n"
_text := _text + tostring(days_til_expiration) + " DAYS TIL "
_text := _text + tostring(_month) + "/" + tostring(_day) + " EXPIRATION"+ "\n"
_text := _text + "STRIKE PRICE: $" + tostring(abs(strike_price)) + "\n"
_text := _text + emoji + " " + (above_strike? "$" + tostring(dollars_itm) + " IN THE MONEY": "$" + tostring(dollars_itm) + " OUT OF THE MONEY") + " " + emoji + "\n"
_text := _text + (chart_flipped ? " PUT OPTION " : " CALL OPTION ")

var tooltip_text = ""
tooltip_text := "Script Information:" + "\n"
tooltip_text := tooltip_text + "version: {{ version }}" + "\n"
tooltip_text := tooltip_text + "processed date: {{ processed_date }}" + "\n"
tooltip_text := tooltip_text + "tickers: [{{ first_ticker }} -> {{ last_ticker }}]"

if show_indicator
    Label := label.new(label_x_position, label_y_position, _text, yloc=yloc.price, xloc=xloc.bar_time, style=label.style_none, textcolor=position_color, size=size.huge, tooltip=tooltip_text)
