//@version=4
study("vline() Function for Pine Script v4.0+", overlay=true)

DAY = timestamp(2020, 8, 25, 0, 0, 0)

PRICE = 75

STYLE = line.style_dashed
ABOVE_STRIKE = close[0] > PRICE
BELOW_STRIKE = close[0] < PRICE
COLOR = BELOW_STRIKE ? color.new(color.red, 0) : color.new(color.green, 0)

line.new(x1=bar_index[0], y1=PRICE, x2=bar_index[1], y2=PRICE, xloc=xloc.bar_index, extend=extend.both, style=STYLE, color=COLOR)

a = plot(PRICE, color= BELOW_STRIKE ? color.new(color.red, 100) : color.new(color.green, 100))
b = plot(ohlc4, color= BELOW_STRIKE ? color.new(color.red, 100) : color.new(color.green, 100))

fill(a, b, color = ABOVE_STRIKE ? color.green : color.red)

line.new(x1=DAY, y1=0, x2=DAY, y2=100, xloc=xloc.bar_time, extend=extend.both, style=STYLE, color=COLOR)

var l = label.new(bar_index, PRICE, text="", style=label.style_none)
label.set_xy(l, bar_index, PRICE)
label.set_textcolor(l, textcolor = ABOVE_STRIKE ? color.green : color.red)
label.set_text(l, text=ABOVE_STRIKE ? "ITM" : "OTM")
label.set_size(l, size.huge)
label.set_textalign(l, text.align_left)
