study("vline() Function for Pine Script v4.0+", overlay=true)
days = 10
if barstate.islast
    myLine = line.new(x1=time + (86400000 * days), y1=0, x2=time + (86400000 * days), y2=100, xloc=xloc.bar_time, extend=extend.both)

if barstate.islast
    myLine = line.new(x1=0, y1=75, x2=1, y2=75, xloc=xloc.bar_index, extend=extend.both)


//@version=4
study("vline() Function for Pine Script v4.0+", overlay=true)

DAY = timestamp(2020, 8, 25, 0, 0, 0)
PRICE = 75


if barstate.islast
    ex = line.new(x1=DAY, y1=0, x2=DAY, y2=100, xloc=xloc.bar_time, extend=extend.both)
    v = line.new(x1=0, y1=PRICE, x2=1, y2=PRICE, xloc=xloc.bar_index, extend=extend.both)
    t = line.new(x1=time, y1=close, x2=DAY, y2=PRICE, xloc=xloc.bar_time, extend=extend.both)
